#=============================
# Spring Properties
#=============================
spring:
  profiles:
    active: local

server:
  echo: 엄준식은 살아있다.

#=============================
# ELK Properties
#=============================
es:
  url: search-mashup-spring-search-5stojescxljz22frzubuuqpauu.ap-northeast-2.es.amazonaws.com
  port: 443
  scheme: https

#=============================
# Eureka Properties
#=============================
# 유레카 클라이언트 아직 사용 X
eureka:
  client:
    enabled: false

#유레카 사용 시 설정들
#server:
#  port: 0
#
#spring:
#  application:
#    name: search-service
#
#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
server:
  echo: 엄준식은 살아있다.

#=============================
# Local Environment
#=============================
---
spring:
  config:
    activate:
      on-profile:
        - local

es:
  url: localhost
  port: 9200
  scheme: http
---
